//ARREDONDAMENTO:

let numero = 4.7

console.log(Math.round (numero)) // Arredonda os números, no caso 4,7 vira 5

//----------------------------------------------------------------------------------------

let numero2 = 7.1

console.log(Math.ceil (numero2)) // Ele sempre arredonda para cima, no caso 7,1 vira 8

//----------------------------------------------------------------------------------------

let numero3 = 7.99

console.log(Math.floor (numero3)) //Ele sempre arredonda para baixo, no caso 7,99 vira 6



//////////////////////////////////////////////////////////////////////////////



//OPERAÇÕES MATEMATICAS:

console.log(Math.pow(5, 2)) //Potenciação (numero, potencia)

console.log(Match.sqrt(35)) //Raiz quadrada do numero

console.log(Match.abs(-5)) //Transforma tudo em positivo

console.log(Math.min(7,45,89,2,125)) //Acha o menor numero entre os digitados, no caso é 2
console.log(Math.max(7,45,89,2,125)) //Acha o maior numero entre os digitados, no caso é 125



////////////////////////////////////////////////////////////////////////////////



//ALEATORIO

let numero_aleatorio = Math.random() //gera um numero aleatorio de 0 a 0,99999999...

console.log(numero_aleatorio)

//-----------------------------------------------------------------------------------

Math.floor(Math.random() * 10) //Gera um número de 0 a 10










